apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-library
  template:
    metadata:
      labels:
        app: book-library
    spec:
      containers:
        - name: book-library-container
          image: openjdk:11-jre-slim
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: secret-volume
              mountPath: /app/secret
      volumes:
        - name: config-volume
          configMap:
            name: book-library-config
            items:
              - key: application.properties
                path: application.properties
        - name: secret-volume
          secret:
            secretName: book-library-secret
